### ISSUE TITLE
Improve loading time for images

### ISSUE THREAD

**Issue by wrussell1999** [MLH-Fellowship/pod-4.1.5-portfolio#2]
Currently, images take a while to load as they're quite large. Can we compress the images when they are committed using a GitHub action to improve loading speeds?

**Comment by Shikhar15606** [comment]
@wrussell1999 I would like to work on this issue with my team.

**Comment by gauravdas014** [comment]
@khattakdev can you assign this issue to @gauravdas014  and @akshatdalton. We are already done with the previous issue.

How are we gonna do this one?
We will use GitHub action (https://github.com/calibreapp/image-actions). This will automatically compress the image files and will help us optimizing image loading time.
