### ISSUE TITLE
Fix the header

### ISSUE THREAD

**Issue by khattakdev** [MLH-Fellowship/pod-4.1.5-portfolio#24]
There is no need for Fellows' photos in the header section. 

![image](https://user-images.githubusercontent.com/37709578/141474965-cd0bf453-9608-4453-bbcf-266ac5462593.png)

It should be removed

**Comment by ricardoprins** [comment]
#22 is dealing with that.

**Comment by ricardoprins** [comment]
This can be closed with #22
