### ISSUE TITLE
Add header background

### ISSUE THREAD

**Issue by wrussell1999** [MLH-Fellowship/pod-4.1.5-portfolio#3]
At the moment, the header background is a colour. Have an option to add an image that's easy to swap to something else and works on multiple screen sizes.

**Comment by khattakdev** [comment]
@jgarcia45 @junhee20park @justbustin What's the progress update on this?

**Comment by jgarcia45** [comment]
We had a question @khattakdev 

Do you just want us to change the background or add a button for users to change the background?
